### ISSUE TITLE
Adicionar seu nome como colaborador no README.md

### ISSUE THREAD

**Issue by CarlaMSilva** [CarlaMSilva/GCMS-Carla-silva#1]
[Readme](https://github.com/CarlaMSilva/GCMS-Carla-silva/edit/main/README.md)
Olá, professor!
@ramidedantas
Gostaria de solicitar que seu nome fosse adicionado à seção de colaboradores.

**Comment by ramidedantas** [comment]
@CarlaMSilva formate o Readme para ficar parecido com o do meu repositório e inclua seu nome. Depois eu boto o meu.

**Comment by ramidedantas** [comment]
@CarlaMSilva nome adicionado, pode fechar issue.
